apiVersion: v1
kind: Secret
metadata:
  name: ewallet-env
  namespace: ewallet
type: Opaque
data:
  POSTGRES_PASSWORD: MTIzNA==
  POSTGRES_DB: bW9uZXlfbW92ZW1lbnQ=
  POSTGRES_USER: cG9zdGdyZXM=
  DB_HOST: cG9zdGdyZXM=
  DB_PORT: NTQzMg==
  PORT_URL: ODA4MA==
  JWT_SECRET: bW9uZXctd2FsbGV0