apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ewallet-hpa
  namespace: ewallet
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ewallet-app
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
