name: Build & Deploy to DigitalOcean Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Terraform with Terraform Cloud
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}

      # 3. Terraform Init (pakai cloud { ... } backend)
      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      # 4. Terraform Apply (infra + registry + cluster)
      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve -var-file=environments/dev.tfvars

      # 5. Ambil Docker credentials dari Terraform output (langsung JSON)
      - name: Configure Docker for DO Registry
        working-directory: terraform
        run: terraform output -raw docker_credentials > $HOME/.docker/config.json

      # 6. Build & Push Docker Image
      - name: Build & Push Image
        run: |
          REGISTRY=$(terraform -chdir=terraform output -raw registry_endpoint)
          IMAGE="$REGISTRY/ewallet-app:latest"
          echo "🚀 Building image: $IMAGE"
          docker build -t $IMAGE .
          docker push $IMAGE

      # 7. Ambil kubeconfig dari Terraform output
      - name: Write kubeconfig
        working-directory: terraform
        run: terraform output -raw kubeconfig > kubeconfig

      # 8. Setup kubectl
      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: latest

      # 9. Deploy to Kubernetes
      - name: Deploy App
        env:
          KUBECONFIG: ${{ github.workspace }}/terraform/kubeconfig
        run: |
          echo "📦 Deploying to Kubernetes..."
          kubectl apply -f deploy/k8s/
          kubectl rollout status deployment/ewallet-app
